services:
  - type: web
    name: uc-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: "your_bot_token"
      - key: FK_API_KEY
        value: "your_api_key"
      - key: FK_SHOP_ID
        value: "your_shop_id"
      - key: FK_SECRET_KEY
        value: "your_secret_key"
